# Basic
name:               "Fridovich-Keil Lab"
title:              "Fridovich-Keil Lab at UT Austin"
description:        "This is the official website of the Control and Learning for Autonomous Robotics Lab at UT Austin."


# URL
url:                https://clearoboticslab.github.io
baseurl:
#baseurl:            "" #For Root Domain
permalink:          /:year/:month/:day/:title.html

# Markdown
markdown:           kramdown

# Highlighter
highlighter:        rouge

# Navigation
nav:
  - name:           "home"
    href:           "/"
  - name:           "about"
    href:           "/about"
  - name:           "publications"
    href:           "/publications"
  - name:           "people"
    href:           "/people"
#  - name:           "blog"
#    href:           "/blog"
#  - name:           "resources"
#    href:           "/resources"

# Sass
sass:
  style:            :compressed

# Scopes
defaults:
  -
    scope:
      path:         ""
      type:         "pages"
    values:
      layout:       "page"
  -
    scope:
      path:         ""
      type:         "posts"
    values:
      layout:       "post"
  -
    scope:
      path:         ""
      type:         "people"
    values:
      layout:       "profile"

collections:
  people:
    output: true
    permalink: /people/:title/index.html

plugins_dir: [jekyll-scholar]

scholar:
  style: apa #american-institute-of-aeronautics-and-astronautics #modern-language-association  #chicago-author-date #, apa, chicago-author-date, ieee, , nature, vancouver
  locale: en

  sort_by: none
  order: ascending
  group_by: year
  group_order: descending
  bibliography_group_tag: h3
  bibliography_list_tag: ul
  bibliography_item_tag: ul #nobull

  source: ./_bibliography
  bibliography: references.bib
  bibliography_template: bib # "{{reference}}"

  replace_strings: true
  join_strings:    true

  details_dir:    bibliography
  details_layout: bibtex.html
  details_link:   Details

  query: "@*"
